language: r
sudo: false

r_github_packages:
  - mlr-org/farff
  - mlr-org/mlr
  - berndbischl/BBmisc
  - berndbischl/ParamHelpers
  - r-lib/httr

cache:
  packages: true
  directories:
    - $HOME/.openml/cache

before_script:
  - mkdir -p "$HOME/.openml/cache" && find "$HOME/.openml/cache"
  - echo "apikey=$OPENMLAPIKEY" > "$HOME/.openml/config"
  - R --no-save <<< 'library("devtools"); document()'

after_success:
  - Rscript -e 'library(covr);codecov()'
  - Rscript -e 'pkgdown::build_site()'

notifications:
  email:
    recipients:
        - giuseppe.casalicchio@stat.uni-muenchen.de
    on_success: never
    on_failure: never
  slack:
    rooms:
      - openml:sHBAXvEJBWpSluiYfzSogNFT#buildnotifications
    on_success: change
    on_failure: change
